nikolay-klekto/fs-platform-ru

- fs-platform-ru/CODEOWNERS
Add ability to review changes from mallarion and fun scrut account
> Add new code owner

- .idea/.gitignore
- .idea/FunscrutRU.iml
- .idea/modules.xml
- .idea/vcs.xml
- fs-platform-ru/backend/domain/ru-client/src/main/resources/ru-client.yaml
> first commit

- fs-platform-ru/frontend/public/index.html
> AM-FS-1-git_test

- frontend-react/app/globals.css
- frontend-react/app/layout.tsx
- frontend-react/app/page.tsx
- frontend-react/components.json
- frontend-react/components/ui/button.tsx
- frontend-react/components/ui/card.tsx
- frontend-react/components/ui/dialog.tsx
- frontend-react/components/ui/input.tsx
- frontend-react/components/ui/tabs.tsx
- frontend-react/lib/utils.ts
- frontend-react/package-lock.json
- frontend-react/package.json
- frontend-react/tailwind.config.ts
- Added shadcn
- Changed text style to Montserrat as in design
> Added shadcn. Changed text style to Montserrat as in design

- frontend-react/app/page.tsx
- frontend-react/app/personalaccount/page.tsx
- frontend-react/components/desktop/layout/PersonalAccountDesktop/PersonalAccountDesktop.tsx
- frontend-react/components/mobi/layout/PersonalAccountMobi/PersonalAccountMobi.tsx
- frontend-react/styles/customClasses/customClassElements.css
- frontend-react/tailwind-config/backgroundImageConfig.ts
Сделана страница личного кабинета для десктопа и мобильной версии.
> Ff 61 personal aacount

- frontend-react/app/page.tsx
fixed bag with open modal window 
https://github.com/user-attachments/assets/24b4dc99-5dc0-4a76-8723-40884bce7a10
> fix_trainer call modal

- frontend-react/components/desktop/layout/FooterDesktop/FooterDesktop.tsx
- frontend-react/components/desktop/layout/FooterDesktop/contentFooterDesktop.tsx
- frontend-react/components/desktop/layout/ModalDesktop/ModalEventsDesktop/ModalEventsDesktop.tsx
- frontend-react/components/desktop/shared/formInput/EmailInputDesktop.tsx
- frontend-react/components/desktop/shared/formInput/PasswordInputDesktop.tsx
- frontend-react/components/desktop/shared/formInput/PhoneInputDesktop.tsx
- frontend-react/components/mobi/layout/ContactsMobi/ContactsMobi.tsx
- frontend-react/components/mobi/layout/FooterMobi/FooterMobi.tsx
- frontend-react/components/mobi/layout/HeaderMobi/HeaderMobi.tsx
- frontend-react/components/mobi/layout/LoginModalMobi/LoginModalMobi.tsx
- frontend-react/components/mobi/layout/ModalMobi/ModalCallMobi.tsx
- frontend-react/components/mobi/layout/RegistrationModalMobi/RegistrationModalMobi.tsx
- frontend-react/components/mobi/pageMobi/ProfessionsPageMobi/ProfessionSendMobi.tsx
- frontend-react/components/mobi/shared/formInput/EmailInputMobi.tsx
- frontend-react/components/mobi/shared/formInput/PasswordInputMobi.tsx
- frontend-react/components/mobi/shared/formInput/PhoneInputMobi.tsx
- frontend-react/components/ui/button.tsx
- frontend-react/components/ui/modal.tsx
1. удалила неиспользуемые пути
2. подправила компонент modal
> refactor: delete some paths

- frontend-react/components/desktop/layout/ProfessionsSectionDesktop/ProfessionSendDesktop.tsx
Исправлена проблема с вводом текста
> FF-67 fix text input

- frontend-react/components/desktop/layout/HeaderDesktop/HeaderDesktop.tsx
- frontend-react/components/mobi/layout/HeaderMobi/HeaderMobi.tsx
Добавила ссылку на логотип (в хедере) для перехода на главную страницу для desktop и mobi
desktop:
https://github.com/user-attachments/assets/5869ff30-3af0-4d83-bc70-739d67210904
mobi:
https://github.com/user-attachments/assets/422f17b3-1208-4441-9201-555a95c245c7
> FF-77 add link to logo (header)

- frontend-react/components/desktop/pageDesktop/ProfessionsPageDesktop/ProfessionsSelectDesktop.tsx
Подключила закрытие селектора при клике вне его области для декстопа
https://github.com/user-attachments/assets/8079eae9-4488-4ac9-8668-a71463bb9143
> Ff 76 fix/close selector

- frontend-react/components/desktop/pageDesktop/HomePageDesktop/HomePageDesktop.tsx
1. Добавлен градиент на главную страницу в HomePageDesktop.
> FF-81-bg-HeaderMainDesktop

- frontend-react/modals/ModalsDesktop/ModalCallDesktop.tsx
1. Центрировала заголовок.
2. Изменила толщину бордеров инпутов и их высоту согласно макету.
3. Исправила чекбокс в соответствии с макетом (но есть проблема - чекбокс на нажатие реагирует, текст становится полужирным, но галочка не убирается).
4. Исправила название поля, вместо Телефон - Номер телефона, в том же инпуте исправила текст placeholder'а на шаблон номера.
5. Строку “Защита от спама reCAPTCHA…” поставила к левому краю и сверху добавила отступ согласно макету. 
6. Увеличила отступ под вторым инпутом в соответствии с макетом.
7. Исправила высоту кнопки Оставить заявку согласно макету, проверила толщину и размер шрифта этой кнопки.
8. Исправила цвет сообщения в случае ошибки.
9. Убрала изменение бордера инпутов при фокусе.
10. Убрала текст "Заполните поля - и мы с вами свяжемся", …
> FF-97-fix-ModalCallDesktop

- frontend-react/app/page.tsx
- frontend-react/components/desktop/layout/ModalDesktop/ModalCookieDesktop.tsx
- frontend-react/package-lock.json
Удалено появление окна куки при обновлении страницы в Desctop.
> ff-100/changed app/page, MadalCookieDesktop; cookies removed on update

- frontend-react/components/desktop/layout/ProfessionModalDesktop/NotifyModalDesktop.tsx
- frontend-react/components/desktop/pageDesktop/EventsPageDesktop/EventsSelectSearchDateDesctop.tsx
- frontend-react/components/mobi/pageMobi/EventsPageMobi/EventsCardMobi.tsx
- frontend-react/components/mobi/pageMobi/EventsPageMobi/EventsPageMobi.tsx
- frontend-react/components/mobi/pageMobi/EventsPageMobi/EventsSelectSearchCityMobi.tsx
- frontend-react/next.config.mjs
Убрала настройку в next.config.mjs `output: 'export'`, результат можно оценить только после деплоя.
> FF-105 fix 404error in reloading pages

- frontend-react/README.md
- frontend-react/README_en.md
- frontend-react/components/assets/icons.tsx
- frontend-react/components/assets/iconsMobi.tsx
1. Добавила в файлы README.md правило именования интерфейсов
2. Переименовала интерфейсы в файлах иконок.
> Update README, rename interfaces in icon files

- frontend-react/components/desktop/layout/ProfessionModalDesktop/ItemCompaniesDesktop.tsx
- frontend-react/package-lock.json
Исправлено позиционирование контента **InternshipCompaniesModelDesktop** внутри компонента **ProfessionModalDesktop**.
- 1025px
-1240px
-1441px
> FF-112-ProfessionModelDesktop content positioned

- frontend-react/components/desktop/layout/ProfessionsSectionDesktop/ProfessionsSectionDesktop.tsx
commented(hid) section ProfessionSendDesktop in ProfessionsSectionDesktop.tsx
> FF-127_deleteform_homedesktop

- frontend-react/modals/ModalsMobi/ModalCallMobi.tsx
В modals/ModalsMobi/ModalCallMobi.tsx внутри состояния accepted добавила переход на страницу "Профессии" при клике по кнопке "Смотреть".
Также добавила событие onClick={onClose} на кнопке, чтобы модалка закрывалась при этом клике.
> FF-131_look_proffbtn_mobi

- frontend-react/app/personal-account/page.tsx
- frontend-react/components/desktop/pageDesktop/HomePageDesktop/components/ProfessionSectionDesktop/ProfessionsSectionDesktop.tsx
- frontend-react/components/desktop/pageDesktop/PesronalAccountPageDesktop/components/OrderPayment/OrderPaymentDesktop.tsx
Исправила ошибки, приложение билдится. Есть предупреждения TW о порядке стилей.
Прикладываю успешные статусы сборки, сейчас некоторые страницы немного тяжело весят при первой загрузке
> FF-132-solve-build-errors

- frontend-react/components/desktop/layout/FooterDesktop/FooterDesktop.tsx
- frontend-react/components/mobi/pageMobi/HomePageMobi/components/HeaderMainMobi/HeaderMainMobi.tsx
исправлены импорты для иконок в footer десктопа и header мобильной версии
> import paths fixed

- frontend-react/app/personal-account/page.tsx
- frontend-react/components/desktop/pageDesktop/PesronalAccountPageDesktop/PersonalAccountPageDesktop.tsx
- frontend-react/components/desktop/pageDesktop/PesronalAccountPageDesktop/components/OrderPayment/OrderPaymentDesktop.tsx
- frontend-react/components/desktop/pageDesktop/PesronalAccountPageDesktop/components/RequiringPaymentDesktop/RequiringPaymentDesktop.tsx
1) На десктопной версии страницы “personal-account” (components/desktop/pageDesktop/PesronalAccountPageDesktop/PersonalAccountPageDesktop.tsx) добавила footer. 
2) На странице "personal-account" (app/personal-account) добавила нужные импорты компонентов PersonalAccountPageDesktop и PersonalAccountPageMobi, а также исправила их вызов (вместо мобильной версии PersonalAccountPageMobi вызывался "ProfilePageMobi", вместо десктопной версии PersonalAccountPageDesktop вызывался "ProfileAccountDesktop").
3) Неверно была прописана ширина экрана для декстопной версии personal-account: вместо минимальной ширины в 769 пикселей была прописана ширина 768 пикселей, в связи с чем в мобильной версии при экране в размере 768 пикселей страница уезжала. Прикладываю скрины до и после правок.
4) Кнопка …
> FF-145-fix-footer-desktop

- frontend-react/components/desktop/pageDesktop/HomePageDesktop/components/EventsSectionDesktop/EventsSectionDesktop.tsx
- frontend-react/components/desktop/pageDesktop/HomePageDesktop/components/EventsSectionDesktop/ItemEventsDesktop/ItemEventsDesktop.tsx
Add event card shadow and pointer on descktop.
Добавлена тень для карточек мероприятий.
> FF-142-add-event-card-shadow-desktop

- frontend-react/components/mobi/pageMobi/JoinTeamPageMobi/components/JoinTeamMobi.tsx
> FF-171-fix-build: fix build error

- frontend-react/components/mobi/pageMobi/JoinTeamPageMobi/components/JoinTeamMobi.tsx
Переход "Назад" в окне "ХОТИТЕ РАБОТАТЬ У НАС?" работает
> FF-185 fix for back button on the phone

- frontend-react/components/ui/input.tsx
- frontend-react/modals/ModalsDesktop/ModalCallDesktop.tsx
- frontend-react/modals/ModalsMobi/ModalCallMobi.tsx
- Adjusted margins in both mobile and desktop versions
- Implemented label color change on checkbox toggle
- Fixed checkbox functionality in mobile version
- Ensured consistent behavior across all modal windows"
> FF-228-feat/ui-input-label-toggle

- frontend-react/modals/ModalsDesktop/ModalJoinTeamDesktop.tsx
1. Реализована отправка формы в модальном окне "Хочу в команду". 2. Добавлено toast-уведомление, которое появляется после успешной отправки формы. 3. Проверка выполнена вручную через npm run dev. 4. Изменения внесены только в файл ModalJoinTeamDesktop.tsx. 5.Скриншот результата прикреплён ниже.
> FF-184-fix Modal Join Team Desktop: submission and toast

- frontend-react/components/desktop/layout/FooterDesktop/FooterDesktop.tsx
- frontend-react/components/mobi/layout/FooterMobi/FooterMobi.tsx
Поскольку в футере временно закомментирована юр часть, необходимо было законмментировать и импорты неиспользуемых компонентов, что ломало билд
components/desktop/layout/FooterDesktop/FooterDesktop.tsx
components/mobi/layout/FooterMobi/FooterMobi.tsx
> FF-fix: resolve errors in building

- frontend-react/components/ui/modal.tsx
- frontend-react/modals/ModalsMobi/LoginModalMobi.tsx
- frontend-react/modals/ModalsMobi/ModalCallMobi.tsx
- frontend-react/modals/ModalsMobi/ModalForgotPasswordMobi.tsx
- frontend-react/modals/ModalsMobi/ModalStatusMobi/ModalContractTerminatedMobi.tsx
- frontend-react/modals/ModalsMobi/ModalStatusMobi/ModalOrderAcceptedMobi.tsx
- frontend-react/modals/ModalsMobi/RegistrationModalMobi.tsx
- Добавила в общий компонент Modal проп variant типа 'desktop' | 'mobile' 
- В мобильных модалках передала variant="mobile"
- Внутри Modal использовала variant для условного рендера между desktop и mobile
- использовала в рендере одну картинку заднего фона модалки, унифицировала ее
- удалила дублирующий код
> FF-221-feat/modal-add-mobile-support
